import { Box, Flex, Heading, Text } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";
import SearchBox from "./components/SearchBox";
import { useState } from "react";
import Tweets from "./components/Tweets";
export interface Mention {
  start: number;
  end: number;
  username: string;
  id: number;
}
export interface TweetObject {
  author_id: string;
  id: string;
  text: string;
  entities?: {
    mentions: Array<Mention>;
  };
}
export interface UserInfoObject {
  id: undefined | string;
  location: undefined | string;
  name: undefined | string;
  profile_image_url: undefined | string;
  url: undefined | string;
  username: undefined | string;
}

const Home: NextPage = () => {
  const [tweets, setTweets] = useState<Array<TweetObject>>([]);
  const [userInfo, setUserInfo] = useState<UserInfoObject>({
    id: undefined,
    location: undefined,
    name: undefined,
    profile_image_url: undefined,
    url: undefined,
    username: undefined,
  });
  const [metaInfo, setMetaInfo] = useState<{ next_token: string | undefined }>({
    next_token: undefined,
  });
  const [isLoading, setIsLoading] = useState<boolean>(false);

  return (
    <Flex
      maxW="100%"
      minW="50%"
      w="container.lg"
      direction="column"
      mx="auto"
      alignItems="center"
    >
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Tweet Finder</Heading>
      <Heading fontSize="lg" mt="4" color="gray.600">
        {"Find the user's best Tweets"}
      </Heading>
      <SearchBox
        setIsLoading={setIsLoading}
        isLoading={isLoading}
        setTweets={setTweets}
        setUserInfo={setUserInfo}
        setMetaInfo={setMetaInfo}
      ></SearchBox>
      <Tweets tweets={tweets} userInfo={userInfo} />
    </Flex>
  );
};

export default Home;
